todo/mainapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.views.generic import ListView
from mainapp.models import Job


app_name = 'mainapp'
urlpatterns = [
    url(r'^jobs/$', views.JobList.as_view(), name='jobs'),
    #url(r'^create_job/', views.JobCreateView.as_view(), name='create-job'),
    url(r'^job_create/', views.job_create, name='job-create'), #function view
    url(r'^delete_job/(?P<pk>\d+)/$', views.JobDelete.as_view(), name='delete-job'),
    url(r'^job_deleted/', views.JobDelete.as_view(), name="job-deleted"),
    url(r'^edit/(?P<pk>\d+)$', views.job_update, name='job-edit'),
    url(r'^$', views.JobList.as_view(), name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

todo/todo/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^mainapp/', include('mainapp.urls')),
    url(r'^admin/', admin.site.urls),
]

todo/mainapp/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse
# Create your models here.
# Change your models (in models.py).
# Run python manage.py makemigrations to create migrations for those changes
# Run python manage.py migrate to apply those changes to the database.


class Job(models.Model):
    title = models.CharField(max_length=100)
    start_date = models.DateField(auto_now_add = True)
    finish_date = models.DateField(default=timezone.now)
    
    class Meta:
        ordering = ['finish_date']

    @property
    def days_left(self):
        return ( self.finish_date - datetime.date.today() ).days 
 

    # def __str__(self):
    #     return self.title

todo/mainapp/forms.py
from django import forms
import datetime
from .models import Job
from django.forms.extras.widgets import SelectDateWidget


class CreateJobForm(forms.ModelForm):
    finish_date = forms.DateField(initial=datetime.date.today(),
                                  widget=SelectDateWidget(empty_label=("Choose Year",
                                                                       "Choose Month",
                                                                       "Choose Day"),),)
    title = forms.CharField()

    class Meta:
        model = Job
        exclude = ['start_date']
        #widgets = {'finish_date': forms.SelectDateWidget(empty_label=("Choose Year", "Choose Month", "Choose Day"),)}

    #https://docs.djangoproject.com/en/1.9/ref/forms/validation/#cleaning-a-specific-field-attribute
    def clean(self):
        # make sure the finish date isnt in the past
        # ------------------------------------------
        finish = self.cleaned_data['finish_date']
        now = datetime.date.today()
        if finish < now:
            raise forms.ValidationError('The finish date must be in the future- finish = {0}, -- {1}'.format(type(finish), type(now)), code='invalid finish date')

        return self.cleaned_data

todo/mainapp/views.py
from django.shortcuts import redirect, render, get_list_or_404, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
import datetime
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import DeleteView  # this is the generic view
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import ListView, CreateView
from .models import Job
from .forms import CreateJobForm



class JobList(ListView):
    model = Job
    # days_left = days_left()


def job_update(request, pk, template_name='mainapp/job_form.html'):
    job = get_object_or_404(Job, pk=pk)
    form = CreateJobForm(request.POST or None, instance=job)
    if form.is_valid():
        form.save()
        return redirect('mainapp:jobs')
    return render(request, template_name, {'form':form})

# def job_list(request):
#     jobs = jobs.objects.all()
#     context = {
#         'jobs': jobs
#     }
#     return render(request, 'mainapp/job_list.html', context)


class JobDelete(DeleteView):
    model = Job
    def get_success_url(self):
        return reverse('mainapp:jobs')


def job_create(request):
    args = {}
    if request.method == 'POST':
        form = CreateJobForm(request.POST)
        if form.is_valid():
            # https://docs.djangoproject.com/en/1.9/topics/forms/#field-data
            form.save()
            return HttpResponseRedirect(reverse('mainapp:jobs'))
    # validation is required, empty title field causes error
    else:
        form = CreateJobForm()
    args['form'] = form
    return render(request, 'mainapp/job_form.html', args)

def days_left(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)

def home(request):
    hello = "hello view"
    return HttpResponse(JobList)

todo/mainapp/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html-->
<html>
    <head>
        <title>{% block title %} 2: My Base Template {% endblock %}</title>
        <link rel='stylesheet' href='{% static "base.css" %}' />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        {% block script %} {% endblock %}
    </head>
    
    <body>
        
        <div><!-- Header -->
            <p> this is the header </p>
        </div>

        <div id="sidemenu"><!-- Side Menu -->   
            <ul id="navmenu">
                <li> <a href="http://127.0.0.1:8000/mainapp/job_create/"> Add new Job (fbv)</a></li>
                <li> <a href="http://127.0.0.1:8000/mainapp/jobs/"> display jobs</a></li>
            </ul> 
        </div>

        <div><!-- Main Content -->
            {% block content %} body block default content {% endblock content %}
        </div>

         <div><!-- Footer -->   
            <p> this is the footer </p>
        </div>

    </body>
</html>

todo/mainapp/templates/mainapp/add_job_form.html
ppppp
<form action="/mainapp/display_jobs/" method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

todo/mainapp/templates/mainapp/base.html
{% load staticfiles %}
<!--DOCTYPE html-->
<html>
    <head>
        <title>{% block title %} My Base Template {% endblock %}</title>
        <link rel='stylesheet' href='{% static "css/base.css" %}' />     
    </head>
    
    <body>
        
        <div><!-- Header -->
        </div>

        <div><!-- Side Menu -->   
        </div>

        <div><!-- Main Content -->
            {% block body_block %} body block default content {% endblock %}
        </div>

         <div><!-- Footer -->   
        </div>

    </body>
</html>

todo/mainapp/templates/mainapp/create_job.html
fgdfg

<form action="/mainapp/display_jobs/" method="post">{% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

todo/mainapp/templates/mainapp/job_confirm_delete.html
{% extends "base.html" %}

{% block title %}Confirm deletion of {{ job.title }}{% endblock title %}

{% block content %}

    <h1>Delete Job</h1>

    <p>Are you sure you want to delete the contact {{ job }}?</p>

    <form action="{% url "mainapp:delete-job" pk=job.id %}" method="POST">{% csrf_token %}
        <input type="submit" value="Yes, delete." />
        <a href="{% url "mainapp:jobs" %}">No, cancel.</a>
    </form>

{% endblock content%}

todo/mainapp/templates/mainapp/job_form.html
{% extends "base.html" %}
{% block script %}
    
{% endblock script %}
{% block content %}
    <p>is it working?</p>
    <form action="" method="post">{% csrf_token %}
        {{ form.as_p}} 
        <input type="submit" value="Save" />
    </form>
{% endblock content %}

todo/mainapp/templates/mainapp/job_list.html
{% extends "base.html" %}
{% block title%}
    Jobs
{% endblock title %}
{% block content %}
    <h2>Jobs</h2>
    <table id='joblist'>
        <tr>
            <th>Title</th>
            <th>Start Date</th>
            <th>Finish Date</th>
            <th>Days remaining</th>
        </tr>

        
        {% for job in job_list %}
            {% if job.days_left < 3 %}
                <tr class='deadline-approaching'>
            {% else %}
                <tr>
            {% endif %}
                    <td>{{ job.title }} </td>
                    <td>{{ job.start_date }}</td>
                    <td>{{ job.finish_date }}</td>
                    <td >{{ job.days_left }}</td>
                    <td>{% if job.id and job.days_left < 3 %}
                            <a href="{% url "mainapp:delete-job" pk=job.id %}">Delete</a>
                            <a href="{% url "mainapp:job-edit" pk=job.id %}">Edit</a>
                        {% else %}
                            <a href="{% url "mainapp:delete-job" pk=job.id %}">Delete</a>
                            <a href="{% url "mainapp:job-edit" pk=job.id %}">Edit</a>

                        {% endif %}</td>
                </tr>
        {% endfor %}
    </table>


    
{% endblock content%}

todo/mainapp/templates/mainapp/todo-list.html
<h1>Create new:</h1>
<form action="/your-name/" method="post">>
     <label for="your_name">Your name: </label>
    <input id="your_name" type="text" name="your_name" value="{{ current_name }}">
    <input type="submit" value="OK">
</form>

todo/mainapp/templates/mainapp/todolist.html
<h1>{{ temp_var }}</h1>

<p>this is where the todo list will be displayed,
i have to figure out how to save the submitted data in add job to the db before displaying it in the display jobs page</p>